### ISSUE TITLE
Stage view very slow

### ISSUE THREAD

**Issue by indirect** [laullon/gitx#1]
Your Gitx version is amazing! I really like the changes you have made, it is a big improvement. :)

I have noticed one problem though: when I go to the "Stage" view, the app will become unresponsive, changing my cursor to a beachball. Often, this will last for 3-10 seconds. It makes it difficult to flip back and forth between Gitx and TextMate while editing and staging changes. Is there any chance that this will improve in the future? Thanks for all the new features, I am really enjoying them.

**Comment by laullon** [comment]
I'm working on it...

Thanks.

**Comment by indirect** [comment]
Maybe in the meantime it could simply not refresh every time it gains focus? I don't mind pushing ⌘R and waiting when I need to force a refresh. Thanks for the quick response!

**Comment by laullon** [comment]
You can disable the auto-refresh on the preferences.

**Comment by indirect** [comment]
oh! great. thanks very much. :)

**Comment by laullon** [comment]
Solved in v0.8.1

**Comment by indirect** [comment]
It's much better, thanks for the fix. :) Since there's no download available on github yet, I packaged one up myself if anyone else is interested: http://dl.dropbox.com/u/38235/GitX.zip

**Comment by cartazio** [comment]
awesome! 
when'll the direct DL for the next point release be setup / available via the check for updates ui?

**Comment by laullon** [comment]
in 4 or 5 days..

**Comment by cartazio** [comment]
wonderful.
