### ISSUE TITLE
gitx commit doesn't consistently commit staged changes

### ISSUE THREAD

**Issue by cartazio** [laullon/gitx#10]
It seems to do a better job of doing this correctly if I do a command+R refresh, but not always.

this bug seems to only exist in the 0.8.1 release

**Comment by cartazio** [comment]
will there be a point release in the near future that fixes this? its kinda a blocker for me using your version of gitx :(

**Comment by cartazio** [comment]
is the source of this bug known?
thanks

**Comment by laullon** [comment]
https://github.com/laullon/gitx/issues/24

**Comment by cartazio** [comment]
this problem is still in the new version

i highlight two files, move them over to stage then, switch views, then switch back and they are unstaged again.
this doesn't happen if its one file at a time.
