### ISSUE TITLE
Infinite upgrade

### ISSUE THREAD

**Issue by ColinHebert** [laullon/gitx#100]
It seems there is a problem with the last GitX version and auto update :

```
GitX 0.8.3 is now available -- you have V0.8.3. Would you like to download it now ?
```

![Screenshot](http://i.imgur.com/EhJ9y.png)

**Comment by laullon** [comment]
OSX 10.7 ?

**Comment by ColinHebert** [comment]
Indeed

**Comment by jcoby** [comment]
I get the same thing. Console shows:

7/24/11 7:23:25.144 PM GitX: Sparkle Error: An error occurred while installing the update. Please try again later.
7/24/11 7:23:25.144 PM GitX: Sparkle Error (continued): Sparkle Updater: Possible attack in progress! Attempting to "upgrade" from 0.8.2 to V0.8.3. Aborting update.

**Comment by laullon** [comment]
Solved
Thanks.
