### ISSUE TITLE
Feature request: Simple copy when rolling over a SHA

### ISSUE THREAD

**Issue by mattheworiordan** [laullon/gitx#114]
I frequently need to copy the SHA from a commit, but it's surprisingly difficult to grab in Gitx.  When I try and drag over the SHA I often end up getting more than I intended, or cutting off a few chars.

It would be super useful for a copy icon to appear when rolling over a SHA (or another similar mechanism) which I can click on to copy the commit SHA so that I can paste into whatever I need (normally terminal command line Gitx).

Thanks,

**Comment by Uncommon** [comment]
If you right-click the commit in the history list, there is a Copy SHA command.

**Comment by mattheworiordan** [comment]
Sorry, I have been clicking on the SHA key in the right hand side area as opposed to right clicking on the commit in the list.  Thanks for the pointer and sorry for taking up your time.

**Comment by Uncommon** [comment]
No problem. It's also noted in #89 that the commit SHA shouldn't even be a link.

**Comment by laullon** [comment]
Solved on v0.8.4
