### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by svenwin** [laullon/gitx#118]
CompileC build/GitX.build/Release/GitX.build/Objects-normal/x86_64/PBGitWindowController.o PBGitWindowController.m normal x86_64 objective-c com.apple.compilers.llvmgcc42
cd /Users/svenwinkler/Projekte/gitx
setenv LANG en_US.US-ASCII
/Developer/usr/bin/llvm-gcc-4.2 -x objective-c -arch x86_64 -fmessage-length=0 -pipe -std=c99 -Wno-trigraphs -fpascal-strings -fasm-blocks -Os -mdynamic-no-pic -Wreturn-type -Wunused-variable -isysroot /Developer/SDKs/MacOSX10.6.sdk -fobjc-gc-only -fvisibility=hidden -mmacosx-version-min=10.5 -gdwarf-2 -I/Users/svenwinkler/Projekte/gitx/build/GitX.build/Release/GitX.build/GitX.hmap -F/Users/svenwinkler/Projekte/gitx/build/Release -F/Users/svenwinkler/Projekte/gitx -I/Users/svenwinkler/Projekte/gitx/build/Release/include -Ilibgit2/include -I/Users/svenwinkler/Projekte/gitx/build/GitX.build/Release/GitX.build/DerivedSources/x86_64 -I/Users/svenwinkler/Projekte/gitx/build/GitX.build/Release/GitX.build/DerivedSources -isysroot /Developer/SDKs/MacOSX10.6.sdk -include /var/folders/co/coziZhMiEVSrt4EEVVxQHk+++TI/-Caches-/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-epkppyitruxrsededdfvpqvkpnuy/GitX_Prefix.pch -c /Users/svenwinkler/Projekte/gitx/PBGitWindowController.m -o /Users/svenwinkler/Projekte/gitx/build/GitX.build/Release/GitX.build/Objects-normal/x86_64/PBGitWindowController.o

/Users/svenwinkler/Projekte/gitx/PBGitWindowController.m: In function '-[PBGitWindowController window:willUseFullScreenPresentationOptions:]':
/Users/svenwinkler/Projekte/gitx/PBGitWindowController.m:46: error: 'NSApplicationPresentationAutoHideToolbar' undeclared (first use in this function)
/Users/svenwinkler/Projekte/gitx/PBGitWindowController.m:46: error: (Each undeclared identifier is reported only once
/Users/svenwinkler/Projekte/gitx/PBGitWindowController.m:46: error: for each function it appears in.)
/Users/svenwinkler/Projekte/gitx/PBGitWindowController.m:46: error: 'NSApplicationPresentationFullScreen' undeclared (first use in this function)

I'm on SnowLeopard.

**Comment by Uncommon** [comment]
Looks like you need Lion to build now.

**Comment by svenwin** [comment]
Well.. Let's close.. Thx @Uncommon for the feedback.
