### ISSUE TITLE
Refreshing does not update "master" tag in History view

### ISSUE THREAD

**Issue by indirect** [laullon/gitx#12]
When I add a commit using the "Commit" view, and then switch back to the "History" view, my commit is shown, but tagged as somehow being beyond "master". Even refreshing with ⌘R doesn't update the master tag -- instead, it simply scrolls the view down to the commit that is already tagged master. Here's what the view looks like before I try to refresh:

![history view](https://img.skitch.com/20110318-j8jx93b3p3fjsahn5hhjt36274.jpg)

**Comment by targeter** [comment]
Same here, but for _all_ labels on the tree.

**Comment by targeter** [comment]
Hmm, I think this is a duplicate of https://github.com/laullon/gitx/issues#issue/7

**Comment by sj26** [comment]
+1

**Comment by laullon** [comment]
solved on v0.8.2
