### ISSUE TITLE
Double orphan commits issue

### ISSUE THREAD

**Issue by ColinHebert** [laullon/gitx#131]
There is a small issue when you merge two orphan commits, gitx tends to create interrupted graph.

![issue](http://i.imgur.com/kqwtD.png)

You can look at the blue line in gitX which is the same as the green line in my terminal.

**Comment by Uncommon** [comment]
This looks the same as Uncommon/Xit#9

**Comment by ColinHebert** [comment]
Closing at the project isn't maintained anymore.
