### ISSUE TITLE
remove GitXL

### ISSUE THREAD

**Issue by schmurfy** [laullon/gitx#135]
Hi,
I tried your fork for a while but for different reasons I want to go back to GitX, my problem is that even after removing GitXL from my applications folder and asking GitX to recreate the shell link when I type "gitx" it runs GitXL !

How can I completly remove it ?

**Comment by pmarschik** [comment]
Just type `which gitx | xargs rm` in Terminal and the gitx shell program should be removed.
Then recreate the shell link with GitX.

**Comment by schmurfy** [comment]
unfortunately it does not work, I tried again but already tried that before, what happens with the newly created gitx binary is that if GitX is running everything is fine and the repository is open with it but if GitX is not running then it starts GitXL...
I suppose someone was copied somewhere outside the binary package I already removed.

**Comment by schmurfy** [comment]
I found it, I had to remove a folder in ~/Library/Developer/Xcode starting fir GitX followed by a random string, no idea how it got there but now my old GitX is back !
