### ISSUE TITLE
disappearing history

### ISSUE THREAD

**Issue by mattly** [laullon/gitx#15]
Basically, it's only displaying this: http://dl.dropbox.com/u/330142/Screenshots/ss3jmsz09_s5.png

but only on one of my repos. It's a pretty long-running repo. Doesn't happen on other repos, but if I re-clone this one from one of our remotes, it does the same thing.

Ideas?

**Comment by mattly** [comment]
It turns out one of our devs managed to sneak a ^A control character into his commit message. Rewriting history at this point to remove that isn't really feasible, and gitk, tower, tig, and other branch visualization tools I use handle this with aplomb. Any chance gitx can too? :D

**Comment by laullon** [comment]
Can you create a test repo?

**Comment by mattly** [comment]
here you go: https://github.com/mattly/gitx-ctrl-character-bug-demo

**Comment by RomainMuller** [comment]
Seems it breaks _before_ the stage it displays. I've tried to get the ^A from the string before it gets to the screen, and it was still as broken. My guess would be the ^A breaks some stuff in the pipe stuff...

**Comment by laullon** [comment]
Thanks @mattly for the repo.
