### ISSUE TITLE
gitx opens with file dialog when run from a project folder

### ISSUE THREAD

**Issue by ghost** [laullon/gitx#152]
Version: v0.8.4-8-g0d782b5
OS X: 10.7.2

When gitx is not running and I am in my project's folder (which contains the .git folder), I run gitx from the terminal and first an Open dialog appears and then the window containing my project's log appears behind.  The Open dialog is unnecessary and I must close it before I can continue.

This has been happening for a while since 0.83 (I believe, maybe earlier).

**Comment by vesan** [comment]
I have the same problem.

**Comment by lukeman** [comment]
This can be closed now that #154 is merged. Until the release of the next version, you can work around this simply by disabling "Show open panel on launch" in preferences.

**Comment by ghost** [comment]
Thanks, I've been using the latest git version for a week or so now and it's running great.
