### ISSUE TITLE
Syntax highlighting in Tree View

### ISSUE THREAD

**Issue by webandy** [laullon/gitx#16]
Hello. I'm a Ruby developer so it would be most useful to me to have syntax highlighting for .rb files in the "Tree View" of GitX. In GitX 0.7.1 there is no syntax highlighting for a Ruby file in Tree View.  Here is a screenshot of what that looks like: http://cl.ly/1l2s3S3F1x2e1j0E1X1Z

Thanks!

**Comment by laullon** [comment]
ruby highlighting is supported in 0.8.0+
http://cl.ly/3P3z3c1K3J2J392w143A
http://gitx.laullon.com/
