### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mperham** [laullon/gitx#171]
The last binary release was 7 months ago and has annoying bugs like the File Open on start bug (#154).  Could we get a new 0.8.5 release please?

**Comment by laullon** [comment]
as soon I get some free time to test it.
(you can get the last version an compile it for you ;) )

**Comment by asanghi** [comment]
I'm a bit new to XCode, but i cloned the repo and I was able to open the project in XCode (4.3.2) and hit "Run" which builds the project. It reports that the build succeeded but I'm not able to figure out where the built binary is or how to do a local install. 

Just a few quick pointers will help me run with it.

**Comment by laullon** [comment]
product > archive

Germán Laullón
Web: http://www.laullon.com/

On Thu, Apr 12, 2012 at 2:33 AM, Aditya Sanghi
reply@reply.github.com
wrote:
