### ISSUE TITLE
Gist support

### ISSUE THREAD

**Issue by nilbus** [laullon/gitx#173]
Would you be interested in bringing gist support back? I'm willing to make it happen if you'll accept the feature.

**Comment by laullon** [comment]
sure

**Comment by nilbus** [comment]
Cool. I have gists working in [SciMed/GitX](https://github.com/SciMed/gitx), but your fork has diverged significantly from mine. I see in [history.js:20](https://github.com/laullon/gitx/blob/master/html/views/history/history.js) that `showCommit` gets sent `data` which is rendered as the commit markup, but I can't find where in the project that call to `showCommit` is happening. Could you clarify that for me? I need to add the "Gist it" button there, since the page content is not in [history/index.html like it used to be](https://github.com/SciMed/gitx/blob/experimental/html/views/history/index.html#L18).

**Comment by laullon** [comment]
Can you try to make a "pull request"?

Germán Laullón
Web: http://www.laullon.com/

On Fri, Apr 6, 2012 at 6:42 AM, Edward Anderson
reply@reply.github.com
wrote:

**Comment by nilbus** [comment]
Sure. I have some clean-up I want to do first with the github login interface. Once I find time to do that (in the next several weeks?), I'll submit a pull request that references this issue.
