### ISSUE TITLE
Renames not handled correctly

### ISSUE THREAD

**Issue by digitalresistor** [laullon/gitx#19]
I renamed a file within my repository and when I tried to view it with GitX it didn't show me any output for that commit, when I selected any other commit it worked without issues.

When I went back, modified the file to update something and then git commit --amend'ed it, it showed up properly within GitX.

I can't take any screenshots as I am currently at work. These are the steps to replicate

git mv file1 file2
git commit -a -m "Moved file1 to file2"
gitx

Let me know if there is anything else you need!

**Comment by laullon** [comment]
solved on 0.8.2

**Comment by laullon** [comment]
V0.8.2 beta is out http://gitx.posterous.com/gitx-l-v082-beta
