### ISSUE TITLE
Remove Hide status

### ISSUE THREAD

**Issue by gglanzani** [laullon/gitx#23]
When GitX is hidden (⌘ H) and I ⌘ TAB to it, before removing its hidden status and showing the window, too much time passes (much more than any other application). This happens on both my MacBook Pro (i5) and my iMac (CD), regardless on memory or CPU usage (even though high stresses makes it more evident).

**Comment by laullon** [comment]
Can you check if your mac is swapping?

In future versions I'm going to reduce the memory usage.

**Comment by gglanzani** [comment]
No, even when GitX is the only app running on a mac with 4GB of memory (-> no swapping), I notice this delay.

**Comment by laullon** [comment]
I think I've found the problem.
Can you try to disable the "Refresh automatically" on properties?

**Comment by gglanzani** [comment]
Yes, It works now! Thanks!

Giovanni

On 20 apr. 2011, at 08:43, laullon
reply@reply.github.com
wrote:

**Comment by RomainMuller** [comment]
@laullon: Maybe we should work on making the automated refresh in soft backrgound so it does not interfere with the UI responsiveness?

**Comment by laullon** [comment]
I'm working on it.

**Comment by gglanzani** [comment]
Is it not possibile to use grand central dispatch to pass this update off the main thread, and give it to a secondary worker, so that it can get the job done in an asynchronous way?
