### ISSUE TITLE
Regression: Dragging multiple files from unstaged to staged doesn't work

### ISSUE THREAD

**Issue by marcello3d** [laullon/gitx#24]
If I drag two or more files from the unstaged box to the staged box, it doesn't actually stage them.

Commit will submit a blank commit and move the files back to the unstaged box.

Switching windows also moves the files back to the unstaged box, so it really seems to be doing nothing—running `git status` from the commandline shows nothing as being staged.

When the files are "staged" in this broken state, diff for the files is blank.

Dragging or double-clicking on a _single_ file does stage correctly, but that means the only workaround is staging files one at a time or through commandline.

This works fine on the brotherband fork, and makes this fork pretty much unusable for me.

**Comment by marcello3d** [comment]
Addendum: Right-clicking and doing "stage changes" does _not_ work either.

**Comment by cartazio** [comment]
this has been seen by a bunch of people, one thing that seems to make it "work better" is to force a refresh with command+r, but that doesn't consistently help. maybe the code was changed to "defer" doing certain manipulations like staging in a way that doesn't quite work idk.

**Comment by jgeiger** [comment]
It also fails if you highlight a group of files and double click on them. The files move over, and you can run a commit (which saves btw) and then a refresh shows the files back on the left. The only way I got this to work was to double click on each file one by one. This alone is enough of a reason for me to stick with an older build.

**Comment by darconeous** [comment]
For what its worth, I don't remember seeing this regression in d609816789f0acfaf85e6a91a92e8c781f04207f, which is the copy I'm using at work. At home, with top-of-tree, I'm definitely having this problem.

**EDIT:** Nevermind. This issue was filed on April 8th. d609816789f0acfaf85e6a91a92e8c781f04207f is from April 29th. Clearly the problem predates that commit.

**Comment by darconeous** [comment]
[Here is a fix](https://github.com/laullon/gitx/pull/48).
