### ISSUE TITLE
diff view bug

### ISSUE THREAD

**Issue by burningTyger** [laullon/gitx#3]
I translate stuff in some projects so it is nice to diff the docs since my last translation efforts to see what changed. I wanted to use your GitX to diff that date with Head and work in an editor. However after switching back from my editor to see more changes in the diff GitX reverted the diff view to the normal tree view. So I have to always select the file again which I want to diff when I unfocus and then refocus on GitX. Could you make the diff view sticky, please?

**Comment by laullon** [comment]
Which gitX version are you using?

**Comment by burningTyger** [comment]
the current download 0.8.1. As I said, open a project, diff any commit with head, go to finder, go back to gitx and your diff is gone.

**Comment by laullon** [comment]
ok, I get it... an it's solved on 0.8.2

**Comment by burningTyger** [comment]
ah, thanks. It happens all the time to me that I want to check what's going on between commits and it was quite annoying to always find the commit again :)
Thanks a lot for fixing this and doing a great job on gitx in general! It's highly appreciated!

**Comment by laullon** [comment]
Thanks...

Meantime, you can disable auto refresh on preferentes.

**Comment by laullon** [comment]
V0.8.2 beta is out http://gitx.posterous.com/gitx-l-v082-beta

**Comment by laullon** [comment]
V0.8.2 beta is out http://gitx.posterous.com/gitx-l-v082-beta

**Comment by burningTyger** [comment]
nice, thanks.

**Comment by burningTyger** [comment]
In 0.8.2 this bug reappears again. This time not only in diff views but in any commit view.
To reproduce view any file in any commit but HEAD and switch back and forth with Finder or any other app. Current view always switches to HEAD.
