### ISSUE TITLE
Is it possible to remove SVN stuff from the bottom bar?

### ISSUE THREAD

**Issue by firedev** [laullon/gitx#31]
Like have an option or something

**Comment by RomainMuller** [comment]
I agree it'd be nice to make them invisible instead of disabled when it's not looking at a git-SVN repo.

**Comment by tekkub** [comment]
Aye, detect if the repo is a git-svn repo and hide those if it's not.  Some of us haven't had to deal with svn directly for years ^^

**Comment by laullon** [comment]
included on 0.8.2
