### ISSUE TITLE
GitX can't quit on rightclick>quit

### ISSUE THREAD

**Issue by firedev** [laullon/gitx#33]
Tried to pull the previous version from the Time Machine, but managed to do this only after I did force quit GitX. Dock right-click > Quit didn't quite impress it.

**Comment by laullon** [comment]
from Time Machine? 
Can you explain it a little more?

**Comment by firedev** [comment]
Nevermind that, basically it didn't quit when I rightclicked it, so had to cmd-opt-Esc it
