### ISSUE TITLE
Loose focus on GitX loose focus on your commit

### ISSUE THREAD

**Issue by emancu** [laullon/gitx#35]
If you select a commit to see differences, and switch to another app (lets say firefox or vim ) and switch back to GitX the view is rendered again and you loose focus on your previous selected commit

**Comment by laullon** [comment]
which gitx version?

**Comment by emancu** [comment]
I just downloaded from your site, GitX-L_v0.8.1

**Comment by laullon** [comment]
Try with the 0.8.2 beta
http://gitx.posterous.com/gitx-l-v082-beta

**Comment by emancu** [comment]
The error stills in  0.8.2 beta :S

**Comment by laullon** [comment]
disable the auto refresh on preferentes.

I'm planing to refactoring the refresh system, but it'll take a while.
