### ISSUE TITLE
branch names with slash

### ISSUE THREAD

**Issue by donpark** [laullon/gitx#4]
GitX fails to display repos if branches names contain slash (like git-flow names feature branches like `feature/foobar`. BrotherBard fork doesn't have this problem.

**Comment by laullon** [comment]
How it fails?
Can you explain it more?
maybe some screenshot...

**Comment by donpark** [comment]
[Here](http://www.flickr.com/photos/donpark/5507594454/) is a screenshot. Basically showing blank.

**Comment by laullon** [comment]
solved 0.8.1
