### ISSUE TITLE
Open in FileMerge link doesn't always work

### ISSUE THREAD

**Issue by delfuego** [laullon/gitx#41]
I'm running GitX 0.8.2_beta on OS X 10.6.7, and the "open in FileMerge" link in the commit details window doesn't always work. Most of the time, it works for the first listed file -- e.g., if the commit contains five files, the "open in FileMerge" link works for the first file, but not for the remaining four. But sometimes, it _does_ work for other files -- and other times, it _doesn't_ work for the first-listed file.

I don't know whether there's available logging I could be sending you, but if there is, please let me know how to access it...

Thanks.

**Comment by laullon** [comment]
What "it doesn't work" means?

**Comment by delfuego** [comment]
Sorry -- as a developer myself, I am apparently my own worst enemy. :)

Clicking the "open in FileMerge" icon or link doesn't do anything; there's no UI response, FileMerge doesn't launch, and there's no obvious error. So far as I can tell, there's also nothing thrown into any of the obvious log files (system.log, etc.).

**Comment by laullon** [comment]
ok ;)

**Comment by laullon** [comment]
Problem found and solved.... ;)
