### ISSUE TITLE
Jumps to last selected commit

### ISSUE THREAD

**Issue by digitalresistor** [laullon/gitx#42]
I've noticed this happening in 0.8.2 (beta). If I select a commit pretty far down the list, I switch applications and switch back, now suddenly instead of looking at where I had scrolled to, the commit I last selected is now the top most item.

I tend to use GitX to view history while git rebasing so I can clean up all the commits I didn't mean to make, and it is rather annoying to get flung down to the last selected commit when attempting to select a more recent commit.

**Comment by laullon** [comment]
You need to disable auto refresh on preferences.
