### ISSUE TITLE
GitX on 10.5.8

### ISSUE THREAD

**Issue by svnlto** [laullon/gitx#6]
the app seems to start find, but when I try to open a repo nothing really happens.
There is console output tho:

11/03/2011 09:07:28 GitX[5951] Could not connect the action discussGitX: to target of class ApplicationController 
11/03/2011 09:07:43 GitX[5951] remote.title="git-svn" 
11/03/2011 09:07:44 GitX[5951] **\* -[PBGitSVOtherRevItem setAlert:]: unrecognized selector sent to instance 0x80044b700 
11/03/2011 09:07:44 GitX[5951] An uncaught exception was raised

11/03/2011 09:07:44 GitX[5951] **\* -[PBGitSVOtherRevItem setAlert:]: unrecognized selector sent to instance 0x80044b700 
11/03/2011 09:07:44 GitX[5951] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[PBGitSVOtherRevItem setAlert:]: unrecognized selector sent to instance 0x80044b700' 
11/03/2011 09:07:44 GitX[5951] Stack: (
    140735359101724,
    140735385659599,
    140735359128667,
    140735359122148,
    140735359122488,
    4295144911,
    140735364332853,
    140735351361167,
    140735351360849
) 
11/03/2011 09:07:44 [0x0-0x11c11c].nl.frim.GitX[5951] terminate called after throwing an instance of 'NSException'

**Comment by laullon** [comment]
same as https://github.com/laullon/gitx/issues#issue/5
