### ISSUE TITLE
Changes to branches made at the command line don't reflect on GitX

### ISSUE THREAD

**Issue by jipumarino** [laullon/gitx#7]
For example, if a perform a commit in master, the commit appears in the history, but the 'master' label remains in the parent commit. Refreshing doesn't update it. If I switch to Commit view and back to History view it does update.

**Comment by cartazio** [comment]
theres also a related problem where if you do a command line git init
then launch gitx to commit the files, it won't commit them!

**Comment by cartazio** [comment]
though it seems that i've worked around that problem, but it was a bit odd

**Comment by cartazio** [comment]
nevermind, still have that problem, wherein i do a gitx commit, it seems to record it, but then it also doesn't "rmemeber" that, plus git cli doesn't see it either

**Comment by sj26** [comment]
+1

This happens when I commit from within Gitx also.

**Comment by laullon** [comment]
solved on v0.8.2

**Comment by laullon** [comment]
V0.8.2 beta is out http://gitx.posterous.com/gitx-l-v082-beta
