### ISSUE TITLE
Fails to push changes since GitHub invents their Mac client

### ISSUE THREAD

**Issue by jk** [laullon/gitx#83]
Since GitHub changed their ssh auth scheme last night so that they now asks for _password_ **and** _username_ your GitX fork isn't able to push changes. I also reported it to [GitHub Support](mailto:support@github.com).

**Comment by Uncommon** [comment]
I just pushed successfully with 0.7.1.

**Comment by jk** [comment]
Looks like I mixed up several clones… don't why that happend. After cloning them from scratch, the issue is gone. So I can close this one here.
