### ISSUE TITLE
View is reset when switching back to GitX

### ISSUE THREAD

**Issue by thomasdeniau** [laullon/gitx#87]
0.8.2:
- View a particular commit (not the HEAD of the current branch / of the currently selected branch in GitX)
- Switch to another app
- Switch back to GitX
- GitX switches to displaying the HEAD of the currently selected branch, instead of keeping the commit currently being inspected.

**Comment by RomainMuller** [comment]
I can confirm I can reproduce this. I have been a victim of this, though it does not break my workflow too badly so I never bothered filing an issue for it (I thought I'd have some time to fix it myself, but apparently not :D).

**Comment by burningTyger** [comment]
same as this issue here that was fixed in an earlier version: https://github.com/laullon/gitx/issues/3

**Comment by AlekSi** [comment]
There is an options for that which works for me.

**Comment by pwagland** [comment]
@AlekSi: What is that option? This is an issue that also annoys me on occasion.

**Comment by AlekSi** [comment]
@pwagland Something like "auto-refresh". I removed this version of GitX due to #77

**Comment by pwagland** [comment]
@AlekSI Thanks! What I really want is a mix between the two… I want the selection to remain on the same item, but for the history to be automatically updated. But not having the selection move is a good start!

**Comment by AlekSi** [comment]
@pwagland I think it's supposed to work like you want, but there is a bug. Manual Cmd+R is better then nothing.

**Comment by blalor** [comment]
Still broken in 0.8.4, with auto-refresh turned on.
