### ISSUE TITLE
GitX (L) 0.8.1 - crash on start

### ISSUE THREAD

**Issue by alexwall** [laullon/gitx#9]
Hi 

GitX crashes on start when I try to open a git repo which git svn clone. I have to branches on this repo, a develop and a master branch. 

Here is an Apple crash report.

git://gist.github.com/870839.git

**Comment by jralls** [comment]
This is the same as issue 5; I've posted a patch there to fix it.

**Comment by laullon** [comment]
duplicate
https://github.com/laullon/gitx/issues#issue/5
