### ISSUE TITLE
Details view broken on Lion

### ISSUE THREAD

**Issue by sirkitree** [laullon/gitx#96]
After upgrading to Lion, it seems as though the details pane no longer works. I've tried reinstalling, switched back to regular GitX, and then reinstalled GitX(L) again and still have the same results.

 ![Alt Text](https://img.skitch.com/20110722-r48qewsjqp71ndy1xsf5xrwt13.png)

**Comment by laullon** [comment]
You have to recompile GitX L from master.

We are going to release a new version in a few days.

Sent from my iPhone
German Laullon
laullon@gmail.com

**Comment by sirkitree** [comment]
Build fails on master, guess I'll wait for the release.

![](https://img.skitch.com/20110723-xymj5by77px6tfsaewmseydkfr.png)

**Comment by ColinHebert** [comment]
Fixed, should be closed.

**Comment by sheldon** [comment]
I don't think it's been fixed in the built release version, probably best to keep open till then.

@sirkitree: You can fix those build issues by setting up the target build version of OSX to 10.6 instead of "latest". I can't remember exactly how I did that, but I'm sure with some digging you'll find it too. Remember you need to do this for both targets, the app and the command line thingy too.

**Comment by jcoby** [comment]
he released v0.8.3 yesterday on the website which fixes the issue. I had a problem with it crashing a few times when trying to restore windows for some reason but after a few tries it came up and the commit view works again.

i don't think 0.8.3 has hit the auto-updater yet though, there was a problem with its signature (i think).

**Comment by sheldon** [comment]
ah right, thanks for the heads up :) I'm running off a custom compiled
master branch version at the moment, which feels a little "unsafe", but I
guess it is git after all, everything is always recoverable.

**Comment by sirkitree** [comment]
I dont' see the download, but if you change the name of the link to the zip file you can get the new version. This is indeed fixed in v0.8.3

**Comment by ColinHebert** [comment]
The v0.8.3 is available via the auto-updated and also via github https://github.com/downloads/laullon/gitx/GitX-L_v0.8.3.zip

**Comment by bryanchow** [comment]
For your reference, I had the same issue after a software update on Snow Leopard 10.6.8 (not Lion).

GitX-L_v0.8.3.zip seems to have resolved the problem. Thank you :)
